language: python
python:
  - 2.7
before_install: openssl aes-256-cbc -K $encrypted_38bb2f7e569a_key -iv $encrypted_38bb2f7e569a_iv -in odm_tech_rsa.enc -out ~/.ssh/id_rsa -d
install: _ci/install.sh
script: nosetests
deploy:
- provider: script
  script: _ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: _ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a6a547c028c3f4bb44d0
    on_success: always
    on_failure: always
